import assert from 'node:assert/strict';
import { once } from 'node:events';
import { mkdtemp, mkdir, writeFile, rm, symlink, readFile, realpath } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { Context } from '@deepseek-ai/cordis';
import { WebSocket } from 'ws';
import { browseLocalWorkspace } from '../src/local-workspace-browser.js';
import { LocalWorkspaceFileRoutes } from '../src/local-workspace-file-routes.js';
import { LocalWorkspaceHub } from '../src/local-workspace-hub.js';
import { Database } from '../src/db.js';
import { createFieldCrypto } from '../src/encrypt.js';
import type { PlatformConfig } from '../src/config.js';

test('paired file picker, directories and previews use the companion with Shell disabled', { timeout: 20_000 }, async t => {
  const temp = await realpath(await mkdtemp(path.join(os.tmpdir(), 'dsh-file-browser-')));
  const root = path.join(temp, 'computer');
  const placeholder = path.join(temp, 'host');
  await mkdir(path.join(root, 'src'), { recursive: true });
  await mkdir(path.join(root, '空目录'));
  await mkdir(path.join(root, 'node_modules'));
  await mkdir(placeholder);
  await writeFile(path.join(root, 'src', '中文 文件.md'), '第一行\n第二行\n');
  await writeFile(path.join(root, 'node_modules', 'hidden.js'), 'dependency');
  const binary = Buffer.alloc(1024 * 1024 + 19, 7);
  await writeFile(path.join(root, 'image.pdf'), binary);
  const ctx = new Context();
  const db = new Database(path.join(temp, 'db'), createFieldCrypto('test', 'test'));
  db.init();
  const owner = db.createUser('owner', 'hash', 'user');
  const other = db.createUser('other', 'hash', 'user');
  const principal = { source: 'dsh-passwords', id: String(owner.id), username: owner.username, role: 'user' as const };
  db.claimSessionOwner('session-local', owner.id);
  const token = 'x'.repeat(43);
  const workspace = db.createLocalWorkspace({ id: 'browser-workspace', userId: owner.id, token, deviceName: 'computer', workspaceName: 'project', remoteRoot: root, placeholderPath: placeholder, platform: process.platform, shellEnabled: false });
  const header = { id: 'session-local', cwd: placeholder };
  ctx.provide('sessionQuery', { listSessions: async () => [{ header }] } as never);
  let registry = ctx.provide('workspaceRegistry', { list: () => [{ id: 'workspace', path: placeholder }] } as never);
  ctx.provide('connection', { authenticateRequest: async () => principal } as never);
  ctx.provide('typertGateway', { invoke: async () => ({ enabled: true, ignoreFiles: [], workspaceIgnoreFiles: [] }) } as never);
  const config = { gateway: { tls: null }, localWorkspace: { host: '127.0.0.1', port: 0, publicUrl: '', placeholderRoot: path.join(temp, 'paired'), browserMaxEntries: 5000, browserMaxFileBytes: 32 * 1024 * 1024, browserIgnoreDirs: ['node_modules', '.git'] } } as PlatformConfig;
  const hub = new LocalWorkspaceHub(ctx, db, config);
  let socket: WebSocket | undefined;
  t.after(async () => { socket?.terminate(); await hub.dispose(); await ctx.fiber.dispose(); db.close(); await rm(temp, { recursive: true, force: true }); });
  await hub.start();
  const routes = new LocalWorkspaceFileRoutes(ctx, db, hub, config.localWorkspace);
  const invoke = (method: string, args: Record<string, unknown>, identity = principal) => routes.invoke(method, args, identity, new AbortController().signal);
  const file = (method: string, extra: Record<string, unknown> = {}) => invoke(`workspaceFiles/${method}`, { workspaceFileScopeId: header.id, path: '.', ...extra });
  await assert.rejects(file('list'), { code: 'OFFLINE' });
  registry();
  socket = new WebSocket(`ws://127.0.0.1:${hub.connectionInfo().port}`);
  await once(socket, 'open', { signal: AbortSignal.timeout(3000) });
  const ready = once(socket, 'message', { signal: AbortSignal.timeout(3000) });
  socket.send(JSON.stringify({ type: 'resume', protocol: 2, token, workspaceId: workspace.id, root, platform: process.platform, shellEnabled: false, deviceName: 'computer', workspaceName: 'project' }));
  const handshake = JSON.parse(String((await ready)[0]));
  assert.equal(handshake.type, 'ready', JSON.stringify(handshake));
  registry = ctx.provide('workspaceRegistry', { list: () => [{ id: 'workspace', path: placeholder }], resolveByPath: async () => undefined, delete: async () => undefined } as never);
  let operations = 0;
  socket.on('message', async data => {
    const message = JSON.parse(String(data));
    if (message.type !== 'request') return;
    operations++;
    assert.equal(message.operation, 'files');
    try { socket!.send(JSON.stringify({ type: 'response', id: message.id, ok: true, value: await browseLocalWorkspace(root, message.args, new AbortController().signal) })); }
    catch (error) { socket!.send(JSON.stringify({ type: 'response', id: message.id, ok: false, error: (error as Error).message })); }
  });
  const index = await invoke('atFile/search', { agentId: header.id }) as Array<{ path: string; relative: string; kind: string }>;
  assert.ok(index.some(entry => entry.relative === 'src/中文 文件.md'));
  assert.ok(index.some(entry => entry.relative === '空目录' && entry.kind === 'dir'));
  assert.ok(!index.some(entry => entry.relative.startsWith('node_modules')));
  assert.ok(index.every(entry => entry.path.startsWith(placeholder)));
  const listing = await file('list', { path: 'src' });
  const preview = await file('read', { path: path.join(placeholder, 'src/中文 文件.md'), range: { offset: 2, limit: 1 } }) as Record<string, unknown>;
  assert.equal(preview.text, '第二行');
  assert.equal(preview.eof, true);
  const pdf = await file('readAll', { path: 'image.pdf' }) as { data: string; eof: boolean };
  assert.deepEqual(Buffer.from(pdf.data, 'base64'), binary);
  assert.equal(pdf.eof, true);
  assert.equal((await file('readRelated', { path: 'src/中文 文件.md', relativePath: '../image.pdf' }) as { data: string }).data, pdf.data);
  await assert.rejects(file('read', { path: '../outside.txt' }), /outside/);
  await assert.rejects(file('readAll', { path: 'image.pdf', ownerId: other.id }), /Unexpected/);
  const sidebar = await routes.sidebar('fs.tree', { sessionId: header.id, path: placeholder }, { headers: {} }, new AbortController().signal);
  assert.ok((sidebar!.value as { entries: Array<{name:string}> }).entries.some(entry => entry.name === '空目录'));
  const sidebarText = await routes.sidebar('fs.read', { sessionId: header.id, path: 'src/中文 文件.md' }, { headers: {} }, new AbortController().signal);
  assert.deepEqual(sidebarText?.value, { kind: 'text', content: '第一行\n第二行\n', truncated: false });
  const before = operations;
  await assert.rejects(invoke('atFile/search', { agentId: header.id }, { ...principal, id: String(other.id), username: other.username }), /unavailable/);
  assert.equal(operations, before);
  const envelope = await routes.fetch('workspaceFiles/list', new Request('http://localhost/api/workspaceFiles/list', { method: 'POST', body: JSON.stringify({ type: 'client-request', rpcId: 'test-id', method: 'workspaceFiles/list', payload: { args: { workspaceFileScopeId: header.id, path: '空目录' } } }) }), principal);
  const response = await envelope.json();
  const snapshot = { files: index.map(({ relative, kind }) => ({ relative, kind })), listing, preview: { text: preview.text, lines: preview.lines, eof: preview.eof }, emptyDirectory: response.result.value };
  assert.deepEqual(snapshot, JSON.parse(await readFile(new URL('./expected/local-workspace-browser.json', import.meta.url), 'utf8')));
  await hub.revoke(owner.id, workspace.id);
  await assert.rejects(async () => hub.browse(workspace.id, principal, { action: 'list', path: '.' }, new AbortController().signal), { code: 'FORBIDDEN' });
});

test('browser refuses traversal, escaping links, oversized windows and cancellation', async t => {
  const temp = await mkdtemp(path.join(os.tmpdir(), 'dsh-file-confinement-'));
  t.after(() => rm(temp, { recursive: true, force: true }));
  const root = path.join(temp, 'root'); await mkdir(root);
  await writeFile(path.join(temp, 'outside'), 'private');
  await writeFile(path.join(root, 'file'), 'safe');
  const run = (args: Record<string, unknown>, signal = new AbortController().signal) => browseLocalWorkspace(root, args, signal);
  await assert.rejects(run({ action: 'readBytes', path: '../outside' }), { code: 'FORBIDDEN' });
  await assert.rejects(run({ action: 'readBytes', path: 'C:\\outside' }), { code: 'FORBIDDEN' });
  if (process.platform !== 'win32') {
    await symlink(path.join(temp, 'outside'), path.join(root, 'link'));
    await assert.rejects(run({ action: 'readBytes', path: 'link' }), { code: 'FORBIDDEN' });
  }
  await assert.rejects(run({ action: 'readBytes', path: 'file', length: 1024 * 1024 + 1 }), { code: 'INVALID_ARGUMENT' });
  await assert.rejects(run({ action: 'readBytes', path: 'file' }, AbortSignal.abort()), { name: 'AbortError' });
  await assert.rejects(run({ action: 'write', path: 'file' }), { code: 'INVALID_ARGUMENT' });
  assert.equal(await readFile(path.join(root, 'file'), 'utf8'), 'safe');
});
